# Generated by Django 2.2 on 2020-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=55, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nutriscore_grade', models.CharField(max_length=1)),
                ('url', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=255)),
                ('nutriscore_image', models.URLField(max_length=255)),
                ('nutrient_levels', models.URLField(max_length=255)),
            ],
        ),
    ]
