# Generated by Django 2.2.12 on 2020-04-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutriscore_image',
        ),
    ]
