# Generated by Django 2.2.13 on 2020-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_nutriscore_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars_100g',
            field=models.FloatField(null=True),
        ),
    ]
