# Generated by Django 2.2.13 on 2020-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='substitute',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'substitute'), name='unique favorite substitute'),
        ),
        migrations.AlterModelTable(
            name='substitute',
            table='substitute',
        ),
    ]
